export const AUTH_SIGNUP_SUCCESS = "AUTH_SIGNUP_SUCCESS";
export const AUTH_SIGNUP_FAIL = "AUTH_SIGNUP_FAIL";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_SIGNIN_SUCCESS = "AUTH_SIGNIN_SUCCESS";
export const USER_AUTH_DETAILS = "USER_AUTH_DETAILS";
export const LOGOUT_USER = "LOGOUT_USER";

export const UPLOAD_SUCCESS = "UPLOAD_SUCCESS";
export const UPLOAD_FAIL = "UPLOAD_FAIL";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_FAIL = "CREATE_POST_FAIL";
export const FETCH_ALLPOSTS_SUCCESS = "FETCH_ALLPOSTS_SUCCESS";
export const ON_LIKE_POST = "ON_LIKE_POST";
export const ON_UNLIKE_POST = "ON_UNLIKE_POST";
export const COMMENT_ON_POST = "COMMENT_ON_POST";
export const DELETE_POST = "DELETE_POST";

export const FETCH_MYPOSTS_SUCCESS = "FETCH_MYPOSTS_SUCCESS";
export const FETCH_MYPOSTS_FAIL = "FETCH_MYPOSTS_FAIL";
export const FETCH_USER_PROFILE_SUCCESS = "FETCH_USER_PROFILE_SUCCESS";
export const FOLLOW_USER = "FOLLOW_USER";
export const UNFOLLOW_USER = "UNFOLLOW_USER";
